services:
  web:
    build: .
    container_name: pipeline-analyzer-web
    ports:
      - "5000:5000"
    volumes:

      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - JENKINS_URL=http://172.17.0.1:8080
      - JENKINS_USER="your_jenkins_username"
      - JENKINS_TOKEN="your_jenkins_api_token"
      - GROQ_API_KEY="your_groq_api_key"

    command: >
      bash -c "poetry install && flask run --host=0.0.0.0 --port=5000"
